-- =============================================================
-- Migration: 001_initial_schema
-- Project:   Real Estate AI Builder
-- Run this in: Supabase Dashboard > SQL Editor > New query
-- =============================================================


-- ─────────────────────────────────────────────
-- 0. ENUM TYPES
-- ─────────────────────────────────────────────

create type public.project_status as enum ('draft', 'published', 'archived');


-- ─────────────────────────────────────────────
-- 1. UTILITY: updated_at auto-trigger
-- ─────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ─────────────────────────────────────────────
-- 2. USERS TABLE
--    Mirrors auth.users — one row per signed-up user.
--    Populated automatically by the handle_new_user trigger below.
-- ─────────────────────────────────────────────

create table public.users (
  id           uuid        primary key references auth.users (id) on delete cascade,
  email        text        not null,
  full_name    text,
  avatar_url   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Automatically update updated_at on every row change
create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

-- Auto-create a profile row whenever someone signs up via Supabase Auth
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.users (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ─────────────────────────────────────────────
-- 3. PROJECTS TABLE
--    One project = one AI-generated real estate website.
--
--    The `config` JSONB column is intentionally schema-less here.
--    It will store the full AI-generated website configuration, including:
--
--    TODO: AI Listing Generation — config shape (to be defined when
--          ListingAgent and SeoAgent are wired up):
--    {
--      "theme":    { "primaryColor": "#...", "font": "..." },
--      "listings": [
--        {
--          "id":          "uuid",
--          "address":     "...",
--          "price":       000000,
--          "bedrooms":    0,
--          "bathrooms":   0,
--          "sqft":        0,
--          "description": "...",   -- generated by ListingAgent
--          "seoTitle":    "...",   -- generated by SeoAgent
--          "seoMeta":     "..."    -- generated by SeoAgent
--        }
--      ],
--      "pages": {
--        "home":    { "headline": "...", "subheadline": "..." },
--        "about":   { "content": "..." },
--        "contact": { "phone": "...", "email": "..." }
--      }
--    }
--
--    TODO: Add a `listings` child table when listing volume justifies
--          moving out of JSONB (>50 listings per project is the threshold).
-- ─────────────────────────────────────────────

create table public.projects (
  id          uuid               primary key default gen_random_uuid(),
  user_id     uuid               not null references public.users (id) on delete cascade,
  name        text               not null,
  slug        text               not null,
  description text,
  status      public.project_status not null default 'draft',
  config      jsonb              not null default '{}'::jsonb,
  created_at  timestamptz        not null default now(),
  updated_at  timestamptz        not null default now(),

  constraint projects_slug_per_user unique (user_id, slug)
);

-- Auto update updated_at
create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

-- Index for the most common query: all projects by a user, newest first
create index projects_user_id_created_at_idx
  on public.projects (user_id, created_at desc);

-- Index for slug lookups (public website routing)
create index projects_slug_idx
  on public.projects (slug);

-- GIN index on config JSONB for fast key lookups once AI data is stored
-- TODO: enable once AI listing generation is active and queries hit config
-- create index projects_config_gin_idx on public.projects using gin (config);


-- ─────────────────────────────────────────────
-- 4. ROW LEVEL SECURITY (RLS)
--    Every table is locked down. Users can only see and modify their own data.
-- ─────────────────────────────────────────────

-- users
alter table public.users enable row level security;

create policy "Users can view their own profile"
  on public.users for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.users for update
  using (auth.uid() = id);

-- projects
alter table public.projects enable row level security;

create policy "Users can view their own projects"
  on public.projects for select
  using (auth.uid() = user_id);

create policy "Users can create projects"
  on public.projects for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own projects"
  on public.projects for update
  using (auth.uid() = user_id);

create policy "Users can delete their own projects"
  on public.projects for delete
  using (auth.uid() = user_id);


-- ─────────────────────────────────────────────
-- 5. PUBLIC READ POLICY (optional — for published sites)
--    TODO: Uncomment when public-facing website previews are built.
--          Lets anonymous visitors read published projects by slug.
-- ─────────────────────────────────────────────

-- create policy "Anyone can view published projects"
--   on public.projects for select
--   using (status = 'published');


-- =============================================================
-- Done. Tables created: users, projects
-- Triggers: set_updated_at (both tables), handle_new_user (auth)
-- RLS: enabled on both tables
-- =============================================================
